"""phase_22_platform_admin

Revision ID: 469e3ea0187f
Revises: 9ebbb61aaae6
Create Date: 2026-09-14 16:36:23.863359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469e3ea0187f'
down_revision: Union[str, None] = '9ebbb61aaae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted: a server_default is required so existing rows (all
    # pre-Phase-22 users) get a value instead of violating NOT NULL.
    op.add_column(
        'users',
        sa.Column('is_platform_admin', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_platform_admin')
    # ### end Alembic commands ###
