"""phase 14: competitor prices

Revision ID: f5ba47685ba0
Revises: c1c9f3b6a2d4
Create Date: 2026-09-14 07:56:52.987460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ba47685ba0'
down_revision: Union[str, None] = 'c1c9f3b6a2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_prices',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('competitor_name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'API', name='competitor_price_source'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_prices_product_id'), 'competitor_prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_competitor_prices_tenant_id'), 'competitor_prices', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_prices_tenant_id'), table_name='competitor_prices')
    op.drop_index(op.f('ix_competitor_prices_product_id'), table_name='competitor_prices')
    op.drop_table('competitor_prices')
    # ### end Alembic commands ###

    # autogenerate creates the enum type inline with the column that uses
    # it but never drops it - without this, downgrading and then
    # upgrading again fails with "type already exists" (see the Phase 1
    # and Phase 2 migrations for the same fix).
    sa.Enum(name='competitor_price_source').drop(op.get_bind(), checkfirst=True)
